### PR TITLE
Provide migration script for converting JSON files

### PR DESCRIPTION
**Pull request by bjhham**
I don't want to go crazy on a Friday afternoon and migrate all the JSON manifests, but here is a script for converting JSON manifest files to the new YAML style cc @VGoncharova

### CODE REVIEW

**Review by e5l — APPROVED** [review]
lgtm, cant' wait all plugins migrated :)

**Comment by e5l** [comment]
please check the CI

**Comment by bjhham** [comment]
It's also broken on main but works locally... Teamcity keeps trolling me.

**Comment by e5l** [comment]
please check if we have jvmToolchain specified

**Comment by bjhham** [comment]
Oh I figured it out, I made a mistake in the test by relying on the resolved artifacts file.  It's expecting 2.3.7 artifacts to be resolved but they're skipped on account of the 2.3.9 release.

**Pull request merged**
